### ISSUE TITLE
Unable to build/open studio

### ISSUE THREAD

**Issue by IncognitoFawkes** [dwijesiri/Bistable-Auxetic-Studio#1]
### there were a couple of issues when I was building the studio, with regards to the file name of the python file included with the .spec file not being what the build required. Renaming the file to Bistable_Auxetic_Studio from whatever it was before helped fix that. After the build was completed, whenever I tried to run the application, a command prompt popped up, had a few lines appear on it, and disappeared almost immediately. It was too fast for me to read or take a screenshot of what the terminal was saying. However, the application itself did not start up.

**Comment by dwijesiri** [comment]
Sorry, I'll fix the .spec file, to direct to the correct source. I believe that the issue you are experiencing is the application trying to search for Logo_1.png and not being able to find it. Did you download it along with everything else? If not, it could be the absence of the pillow module, which I previously forgot to include in dependencies. Thanks!

**Comment by IncognitoFawkes** [comment]
I still can't launch the application. There were two more issues I had to kinda resolve before getting a .exe. The first was the line optimize=0 in line 15 in the .spec file. After deleting that, the build went a bit further until it reached a syntax error in the python file 

else: print(f"Error: {FileSource["Name"]}.baux does not meet the Grid Size Requirements (At least 10 by 10 cells / Smaller than 80 by 40 cells)\n")
                                          ^
 SyntaxError: invalid syntax
 
 
 Where I had to change the double quotes around name to single quotes. That let me build a .exe file in the dist folder, but I wasn't able to launch it. The same thing where a command terminal pops up, shows some lines, and disappears happened. I couldn't read it again, but I think it says module pygame is missing? I tried pip installing that , but  that didn't do anything. I tried to screen record the text, but it was way too fast for the screen recording frame rate.

`PS C:\Users\kolla> cd 'D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source\'
PS D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source> ls


    Directory: D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
------         10/5/2024   5:23 AM            785 Bistable_Auxetic_Studio.spec
------         10/5/2024   5:23 AM          31624 Bistable_Auxetic_Surface_Studio.py
------         10/5/2024   5:23 AM         167629 Logo_1.ico
------         10/5/2024   5:23 AM         785820 Logo_1.png


PS D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source> pyinstaller Bistable_Auxetic_Studio.spec
1146 INFO: PyInstaller: 5.13.2
1146 INFO: Python: 3.7.7
1146 INFO: Platform: Windows-10-10.0.22621-SP0
Traceback (most recent call last):
  File "c:\users\kolla\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kolla\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kolla\AppData\Local\Programs\Python\Python37-32\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\kolla\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "c:\users\kolla\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\kolla\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\kolla\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 1019, in main
    build(specfile, distpath, workpath, clean_build)
  File "c:\users\kolla\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\building\build_main.py", line 944, in build
    exec(code, spec_namespace)
  File "Bistable_Auxetic_Studio.spec", line 15, in <module>
    optimize=0,
TypeError: __init__() got an unexpected keyword argument 'optimize'
PS D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source> pyinstaller Bistable_Auxetic_Studio.spec
692 INFO: PyInstaller: 5.13.2
692 INFO: Python: 3.7.7
692 INFO: Platform: Windows-10-10.0.22621-SP0
706 INFO: Extending PYTHONPATH with paths
['D:\\Storage '
 'Main\\Main\\python\\Bistable-Auxetic-Studio-main\\Bistable-Auxetic-Studio-main\\Source']
1398 INFO: Appending 'datas' from .spec
1398 INFO: checking Analysis
1398 INFO: Building Analysis because Analysis-00.toc is non existent
1398 INFO: Initializing module dependency graph...
1413 INFO: Caching module graph hooks...
1492 INFO: Analyzing base_library.zip ...
4122 INFO: Loading module hook 'hook-heapq.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
4304 INFO: Loading module hook 'hook-encodings.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
5696 INFO: Loading module hook 'hook-pickle.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
10022 INFO: Caching module dependency graph...
10259 INFO: running Analysis Analysis-00.toc
10290 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\kolla\appdata\local\programs\python\python37-32\python.exe
10667 INFO: Analyzing D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source\Bistable_Auxetic_Surface_Studio.py

Syntax error in D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source\Bistable_Auxetic_Surface_Studio.py
  File "D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source\Bistable_Auxetic_Surface_Studio.py", line 607
     else: print(f"Error: {FileSource["Name"]}.baux does not meet the Grid Size Requirements (At least 10 by 10 cells / Smaller than 80 by 40 cells)\n")
                                          ^
 SyntaxError: invalid syntax

PS D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source> pyinstaller Bistable_Auxetic_Studio.spec
709 INFO: PyInstaller: 5.13.2
709 INFO: Python: 3.7.7
709 INFO: Platform: Windows-10-10.0.22621-SP0
709 INFO: Extending PYTHONPATH with paths
['D:\\Storage '
 'Main\\Main\\python\\Bistable-Auxetic-Studio-main\\Bistable-Auxetic-Studio-main\\Source']
1275 INFO: Appending 'datas' from .spec
1275 INFO: checking Analysis
1275 INFO: Building Analysis because Analysis-00.toc is non existent
1275 INFO: Initializing module dependency graph...
1291 INFO: Caching module graph hooks...
1337 INFO: Analyzing base_library.zip ...
3555 INFO: Loading module hook 'hook-encodings.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
4545 INFO: Loading module hook 'hook-heapq.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
5078 INFO: Loading module hook 'hook-pickle.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
7056 INFO: Caching module dependency graph...
7307 INFO: running Analysis Analysis-00.toc
7338 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\kolla\appdata\local\programs\python\python37-32\python.exe
7763 INFO: Analyzing D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source\Bistable_Auxetic_Surface_Studio.py
8015 INFO: Loading module hook 'hook-PIL.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
8141 INFO: Loading module hook 'hook-PIL.Image.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
9177 INFO: Loading module hook 'hook-pycparser.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
10247 INFO: Processing pre-safe import module hook distutils from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-distutils.py'.
10247 INFO: Processing pre-find module path hook distutils from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
10655 INFO: Loading module hook 'hook-distutils.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
10812 INFO: Loading module hook 'hook-distutils.util.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
11315 INFO: Loading module hook 'hook-setuptools.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
13548 INFO: Loading module hook 'hook-importlib_metadata.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
13736 INFO: Loading module hook 'hook-platform.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
14412 INFO: Loading module hook 'hook-packaging.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
14600 INFO: Loading module hook 'hook-sysconfig.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
15782 INFO: Loading module hook 'hook-pkg_resources.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
17669 INFO: Loading module hook 'hook-xml.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
18785 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
20418 INFO: Loading module hook 'hook-numpy.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
21709 INFO: Loading module hook 'hook-difflib.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
24444 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
24510 INFO: Processing module hooks...
25245 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
26413 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
28454 INFO: Looking for ctypes DLLs
28486 INFO: Analyzing run-time hooks ...
28501 INFO: Including run-time hook 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
28518 INFO: Including run-time hook 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
28533 INFO: Including run-time hook 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
28549 INFO: Including run-time hook 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
28564 INFO: Including run-time hook 'c:\\users\\kolla\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_setuptools.py'
28595 INFO: Looking for dynamic libraries
34239 INFO: Looking for eggs
34255 INFO: Using Python library c:\users\kolla\appdata\local\programs\python\python37-32\python37.dll
34255 INFO: Found binding redirects:
[]
34273 INFO: Warnings written to D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source\build\Bistable_Auxetic_Studio\warn-Bistable_Auxetic_Studio.txt
34443 INFO: Graph cross-reference written to D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source\build\Bistable_Auxetic_Studio\xref-Bistable_Auxetic_Studio.html
34589 INFO: checking PYZ
34595 INFO: Building PYZ because PYZ-00.toc is non existent
34595 INFO: Building PYZ (ZlibArchive) D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source\build\Bistable_Auxetic_Studio\PYZ-00.pyz
36061 INFO: Building PYZ (ZlibArchive) D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source\build\Bistable_Auxetic_Studio\PYZ-00.pyz completed successfully.
36109 INFO: checking PKG
36109 INFO: Building PKG because PKG-00.toc is non existent
36109 INFO: Building PKG (CArchive) Bistable_Auxetic_Studio.pkg
43174 INFO: Building PKG (CArchive) Bistable_Auxetic_Studio.pkg completed successfully.
43189 INFO: Bootloader c:\users\kolla\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit-intel\run.exe
43189 INFO: checking EXE
43189 INFO: Building EXE because EXE-00.toc is non existent
43189 INFO: Building EXE from EXE-00.toc
43189 INFO: Copying bootloader EXE to D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source\dist\Bistable_Auxetic_Studio.exe.notanexecutable
43520 INFO: Copying icon to EXE
43530 INFO: Copying icons from ['D:\\Storage Main\\Main\\python\\Bistable-Auxetic-Studio-main\\Bistable-Auxetic-Studio-main\\Source\\Logo_1.ico']
43661 INFO: Writing RT_GROUP_ICON 0 resource with 132 bytes
43661 INFO: Writing RT_ICON 1 resource with 1128 bytes
43661 INFO: Writing RT_ICON 2 resource with 2440 bytes
43661 INFO: Writing RT_ICON 3 resource with 4264 bytes
43661 INFO: Writing RT_ICON 4 resource with 9640 bytes
43661 INFO: Writing RT_ICON 5 resource with 16936 bytes
43661 INFO: Writing RT_ICON 6 resource with 21640 bytes
43661 INFO: Writing RT_ICON 7 resource with 38056 bytes
43661 INFO: Writing RT_ICON 8 resource with 67624 bytes
43661 INFO: Writing RT_ICON 9 resource with 5751 bytes
43678 INFO: Copying 0 resources to EXE
43678 INFO: Embedding manifest in EXE
43678 INFO: Updating manifest in D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source\dist\Bistable_Auxetic_Studio.exe.notanexecutable
43844 INFO: Updating resource type 24 name 1 language 0
43858 INFO: Appending PKG archive to EXE
43880 INFO: Fixing EXE headers
45878 INFO: Building EXE from EXE-00.toc completed successfully.
PS D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source> pip install pygame
Collecting pygame
  Downloading pygame-2.6.1-cp37-cp37m-win32.whl.metadata (13 kB)
Downloading pygame-2.6.1-cp37-cp37m-win32.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 29.7 MB/s eta 0:00:00
Installing collected packages: pygame
Successfully installed pygame-2.6.1
PS D:\Storage Main\Main\python\Bistable-Auxetic-Studio-main\Bistable-Auxetic-Studio-main\Source>`

**Comment by IncognitoFawkes** [comment]
Now that I think about it, there's a chance I pip installed in the wrong place, but I'm gonna try again

**Comment by dwijesiri** [comment]
Hi again. If you can't read the text from the .exe, try running the python file. It should log the error in your terminal and won't close instantly. I built the `.exe` with PyInstaller 6.10.0 and Python 3.12, which may be the cause of your issue. The `optimize = 0` error is because that option is supported from PyInstaller 6.6 and onwards, though you should be able to remove it from the `.spec` file and achieve the same result. If you can, my advice would be updating PyInstaller, and, if possible, python.

**Comment by dwijesiri** [comment]
I've also added the `.exe` file I built in the Executable directory, if you need to use that. Thanks!

**Comment by IncognitoFawkes** [comment]
Will try updating pyinstaller and all soon. Thanks for directly giving the .exe. I feel like it would be easier if you released your code with the .exe you built as a new release, so that it's easier for users who might not have as much experience with python to use the studio itself.

**Comment by dwijesiri** [comment]
Thanks. I'll try and add an `.exe` with every new major update. Looking forward to hear if it worked!

**Comment by IncognitoFawkes** [comment]
Hey
The issue was with tkinter. I did not have that installed.

**Comment by IncognitoFawkes** [comment]
I still didn't get it working though. Also the executable you included worked the first time I tried it, but now I get a error in terminal saying screen size is too small or big, and it doesn't open

**Comment by IncognitoFawkes** [comment]
Couple of things:
The issue I keep getting is consistently with tkinter. I tried pip install tkinter, which didn't work. pip install tk worked for some reason, so this resolved the issue with line 17 in the python file, which was what was causing the initial issue. That line passes without issue when I change tkinter to tk in the python file. However, the same doesn't work in any form for line 18. When it is from tkinter, I get the error saying module named tkinter is not found. When it is from tk, it just says that the command is invalid? So ik from tkinter and import tkinter is the right way of doing it, but I have no idea how to get it working. The python package itself is named tk, and I can't pip install tkinter.

Where are the config values for the unit cell? I primarily want to increase the spacing between lines, and mess with the theta values as I want to laser cut this design, and the current distancing is not good enough for my purposes.

**Comment by dwijesiri** [comment]
Hi. After checking on PyPi, I noticed that tk stands for Tensorkit, which is a deep learning helper library. I believe that tkinter is not installed in your python configuration. If you had the original .exe from which you installed python, you could select the Modify option of the installer, and check the box to install tkinter.

Step #1 (Find Installer):

<img width="517" alt="image" src="https://github.com/user-attachments/assets/2e9fa85b-0662-4be5-b672-1538bf66bd62">
<br>
<br>

Step #2 (Select Modify):

<img width="482" alt="image" src="https://github.com/user-attachments/assets/ed131056-57ea-4cdc-9dac-fe04baaa8f94">
<br>
<br>

Step #3 (Select Tkinter Option):

<img width="488" alt="image" src="https://github.com/user-attachments/assets/a41cdef8-551d-40cb-8f80-b31d346a6d5b">
<br>
<br>
As for the unit cell configuration, you can right click on a cell. This should bring up a box, which lets you tweak the thickness and theta values.
